
package homerenting;

import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Rent extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    private Object DbUtils;
    public Rent() {
        initComponents();
        conn= DbConnection.ConnectDB(); //Database connectivity ..
        listed();
    }
    public void listed()
    {                                     // deafult here for hold data from database
        
     DefaultTableModel table =new DefaultTableModel();
     table.addColumn("Post ID");
     table.addColumn("User Name");
     table.addColumn("Property Type");
     table.addColumn("House Number");
     table.addColumn("Road Number");
     table.addColumn("Block/section");
     table.addColumn("Area");
     table.addColumn("Price");
     table.addColumn("Building Size");
     table.addColumn("Room");
     table.addColumn("Bath");
     table.addColumn("Type Prefer");
     table.addColumn("Contact");
     
     try{
     String sql="SELECT * FROM `building_info`";  //Query Execute here.....
     Statement S=conn.createStatement();
     rs=S.executeQuery(sql);
     
     
     while(rs.next()){
         table.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6),
            rs.getString(7),
            rs.getString(8),
            rs.getString(9),
            rs.getString(10),
            rs.getString(11),
            rs.getString(12),
            rs.getString(13),
            
         });
             
           }
    list.setModel(table);   ///Deafult data Assign Jframe Table data..
     }
     
     catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
     
      
    }
        
    }
    
    
    
    
    public void listed(String area)
    {                                                   //Custom Jtable data retrive from database
     DefaultTableModel table =new DefaultTableModel();
     table.addColumn("Property Type");
     table.addColumn("House Number");
     table.addColumn("Road Number");
     table.addColumn("Block/section");
     table.addColumn("Area");
     table.addColumn("Price");
     table.addColumn("Building Size");
     table.addColumn("Room");
     table.addColumn("Bath");
     table.addColumn("Type Prefer");
     table.addColumn("Contact");
     
     try{                           //Custom query genarate for data hare
     String sql="SELECT * FROM `building_info` WHERE Area= ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,area);
            rs=pst.executeQuery();
     
     
     while(rs.next()){
         table.addRow(new Object[]{  ///Object data move here to Jtable form
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6),
            rs.getString(7),
            rs.getString(8),
            rs.getString(9),
            rs.getString(10),
            rs.getString(11),
         });
             
           }
    list.setModel(table);
     }
     
     catch(Exception e){                 //Exception Handle....
            JOptionPane.showMessageDialog(null,e);
     
      
    }
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Search = new javax.swing.JMenu();
        jRadioButtonLoginAdmin = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonAboutUs = new javax.swing.JRadioButtonMenuItem();
        Bosundhara = new javax.swing.JRadioButtonMenuItem();
        Banani = new javax.swing.JRadioButtonMenuItem();
        Dhanmondi = new javax.swing.JRadioButtonMenuItem();
        Gulsan1 = new javax.swing.JRadioButtonMenuItem();
        Gulsan2 = new javax.swing.JRadioButtonMenuItem();
        Mirpur = new javax.swing.JRadioButtonMenuItem();
        Mahammadpur = new javax.swing.JRadioButtonMenuItem();
        Motijheel = new javax.swing.JRadioButtonMenuItem();
        Uttra = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Post ID", "User Name", "Property Type", "House Number", "Road Number", "Block/section", "Area", "Price", "Building Size", "Room", "Bath", "Type Prefer", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(list);
        if (list.getColumnModel().getColumnCount() > 0) {
            list.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("AVAIBLE HOME NOW");

        back.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-back-filled-40.png"))); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Search.setBorder(null);
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-40.png"))); // NOI18N
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jRadioButtonLoginAdmin.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jRadioButtonLoginAdmin.setSelected(true);
        jRadioButtonLoginAdmin.setText("Price");
        jRadioButtonLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-tags-35.png"))); // NOI18N
        jRadioButtonLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLoginAdminActionPerformed(evt);
            }
        });
        Search.add(jRadioButtonLoginAdmin);

        jRadioButtonAboutUs.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jRadioButtonAboutUs.setSelected(true);
        jRadioButtonAboutUs.setText("Custom Search");
        jRadioButtonAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-google-web-search-35.png"))); // NOI18N
        jRadioButtonAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAboutUsActionPerformed(evt);
            }
        });
        Search.add(jRadioButtonAboutUs);

        Bosundhara.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Bosundhara.setSelected(true);
        Bosundhara.setText("Basundhara");
        Bosundhara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Bosundhara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BosundharaActionPerformed(evt);
            }
        });
        Search.add(Bosundhara);

        Banani.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Banani.setSelected(true);
        Banani.setText("Banani");
        Banani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Banani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BananiActionPerformed(evt);
            }
        });
        Search.add(Banani);

        Dhanmondi.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Dhanmondi.setSelected(true);
        Dhanmondi.setText("Dhanmondi");
        Dhanmondi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Dhanmondi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DhanmondiActionPerformed(evt);
            }
        });
        Search.add(Dhanmondi);

        Gulsan1.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Gulsan1.setSelected(true);
        Gulsan1.setText("Gulshan-1");
        Gulsan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Gulsan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gulsan1ActionPerformed(evt);
            }
        });
        Search.add(Gulsan1);

        Gulsan2.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Gulsan2.setSelected(true);
        Gulsan2.setText("Gulshan-2");
        Gulsan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Gulsan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gulsan2ActionPerformed(evt);
            }
        });
        Search.add(Gulsan2);

        Mirpur.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Mirpur.setSelected(true);
        Mirpur.setText("Mirpur");
        Mirpur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Mirpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MirpurActionPerformed(evt);
            }
        });
        Search.add(Mirpur);

        Mahammadpur.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Mahammadpur.setSelected(true);
        Mahammadpur.setText("Mohammadpur");
        Mahammadpur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Mahammadpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MahammadpurActionPerformed(evt);
            }
        });
        Search.add(Mahammadpur);

        Motijheel.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Motijheel.setSelected(true);
        Motijheel.setText("Motijheel");
        Motijheel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Motijheel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotijheelActionPerformed(evt);
            }
        });
        Search.add(Motijheel);

        Uttra.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        Uttra.setSelected(true);
        Uttra.setText("Uttara");
        Uttra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-marker-20.png"))); // NOI18N
        Uttra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UttraActionPerformed(evt);
            }
        });
        Search.add(Uttra);

        jMenuBar1.add(Search);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(434, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(289, 289, 289)
                .addComponent(back))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
              //RadioButton Actionlistener Implementation
    private void jRadioButtonLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLoginAdminActionPerformed
        new PriceSearch().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jRadioButtonLoginAdminActionPerformed

    private void jRadioButtonAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAboutUsActionPerformed
        new CustomSearch().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jRadioButtonAboutUsActionPerformed

    private void MahammadpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MahammadpurActionPerformed
        listed("Mohammadpur");
    }//GEN-LAST:event_MahammadpurActionPerformed

    private void UttraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UttraActionPerformed
        listed("Uttara");
    }//GEN-LAST:event_UttraActionPerformed

    private void Gulsan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gulsan1ActionPerformed
               listed("Gulshan-1");
    }//GEN-LAST:event_Gulsan1ActionPerformed

    private void BosundharaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BosundharaActionPerformed
            listed("Basundhara");
    }//GEN-LAST:event_BosundharaActionPerformed

    private void MirpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MirpurActionPerformed
        listed("Mirpur");
    }//GEN-LAST:event_MirpurActionPerformed

    private void MotijheelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotijheelActionPerformed
       listed("Motijheel");
    }//GEN-LAST:event_MotijheelActionPerformed

    private void BananiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BananiActionPerformed
       listed("Banani");
    }//GEN-LAST:event_BananiActionPerformed

    private void DhanmondiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DhanmondiActionPerformed
       listed("Dhanmondi");
    }//GEN-LAST:event_DhanmondiActionPerformed

    private void Gulsan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gulsan2ActionPerformed
        listed("Gulshan-2");
    }//GEN-LAST:event_Gulsan2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new SecondHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem Banani;
    private javax.swing.JRadioButtonMenuItem Bosundhara;
    private javax.swing.JRadioButtonMenuItem Dhanmondi;
    private javax.swing.JRadioButtonMenuItem Gulsan1;
    private javax.swing.JRadioButtonMenuItem Gulsan2;
    private javax.swing.JRadioButtonMenuItem Mahammadpur;
    private javax.swing.JRadioButtonMenuItem Mirpur;
    private javax.swing.JRadioButtonMenuItem Motijheel;
    private javax.swing.JMenu Search;
    private javax.swing.JRadioButtonMenuItem Uttra;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonAboutUs;
    private javax.swing.JRadioButtonMenuItem jRadioButtonLoginAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable list;
    // End of variables declaration//GEN-END:variables
}
