
package homerenting;

public class SecondHome extends javax.swing.JFrame {

    /**
     * Creates new form SecondHome
     */
    public SecondHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        offer = new javax.swing.JButton();
        Rent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonhome = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonLoginAdmin = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonAboutUs = new javax.swing.JRadioButtonMenuItem();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        offer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        offer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-triangle-arrow-40.png"))); // NOI18N
        offer.setText("OFFER");
        offer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offerActionPerformed(evt);
            }
        });

        Rent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Rent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-near-me-40.png"))); // NOI18N
        Rent.setText("RENT");
        Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("what would you like to find?");

        jMenu2.setBorder(null);
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-menu-filled-40.png"))); // NOI18N
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jRadioButtonhome.setSelected(true);
        jRadioButtonhome.setText("Home");
        jRadioButtonhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-35.png"))); // NOI18N
        jRadioButtonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonhomeActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonhome);

        jRadioButtonLoginAdmin.setSelected(true);
        jRadioButtonLoginAdmin.setText("Login Admin");
        jRadioButtonLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-admin-settings-male-35.png"))); // NOI18N
        jRadioButtonLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLoginAdminActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonLoginAdmin);

        jRadioButtonAboutUs.setSelected(true);
        jRadioButtonAboutUs.setText("About us");
        jRadioButtonAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-about-35.png"))); // NOI18N
        jRadioButtonAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAboutUsActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonAboutUs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(offer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(offer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Rent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void offerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offerActionPerformed
         new OfferUserlogin().setVisible(true);   //transaction from one JFrame to another........
        this.setVisible(false);
    }//GEN-LAST:event_offerActionPerformed

    private void RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentActionPerformed
      new Rent().setVisible(true);          //transaction from one JFrame to another........
        this.setVisible(false);
    }//GEN-LAST:event_RentActionPerformed

    private void jRadioButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonhomeActionPerformed
        new Home().setVisible(true);         //transaction from one JFrame to another........
        this.setVisible(false);
    }//GEN-LAST:event_jRadioButtonhomeActionPerformed

    private void jRadioButtonLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLoginAdminActionPerformed
        new AdminLogin().setVisible(true);     //transaction from one JFrame to another........
        this.setVisible(false);
    }//GEN-LAST:event_jRadioButtonLoginAdminActionPerformed

    private void jRadioButtonAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAboutUsActionPerformed
        new AboutUs().setVisible(true);          //transaction from one JFrame to another........
        this.setVisible(false);
    }//GEN-LAST:event_jRadioButtonAboutUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rent;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonAboutUs;
    private javax.swing.JRadioButtonMenuItem jRadioButtonLoginAdmin;
    private javax.swing.JRadioButtonMenuItem jRadioButtonhome;
    private javax.swing.JButton offer;
    // End of variables declaration//GEN-END:variables
}
